### ISSUE TITLE
can u tell how can i implement the code and run it in my own pc

### ISSUE THREAD

**Issue by ghost** [simondevyoutube/Quick_3D_RPG#1]

**Comment by NetOpWibby** [comment]
```sh
python3 -m http.server
```

**Comment by thush** [comment]
How to modifiy the .js base .
any documentation please provide..

Thanks.

**Comment by arthurfrp** [comment]
First you need to do is to clone the Github to your machine:

TERMINAL
_git clone https://github.com/simondevyoutube/Quick_3D_RPG.git_
 
after installing it, you need to open the localhost server port (for example port 9000) as follow:

TERMINAL
_python3 -m http.server/9000_

BROWSER
localhost:9000
