### ISSUE TITLE
Python doesn't serve game properly

### ISSUE THREAD

**Issue by XenoMustache** [simondevyoutube/Quick_3D_RPG#2]
Attempting to run the game using the source code from the repository with `python -m http.server` serves the html file without the JavaScript initializing properly. What ends up happening is that the html loads on screen, but the game viewport is completely black.

Screenshot:
<p float="left">
  <img src="https://media.discordapp.net/attachments/326983031149559809/818558741259485214/unknown.png?width=1080&height=545" />
</p>

**Comment by worstpractice** [comment]
@XenoMustache Create a new file (called something like `server.py`) in the root folder of the project.

Paste in the following code:

```python
import http.server
import socketserver

PORT = 8080

class HttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    extensions_map = {
        '': 'application/octet-stream',
        '.manifest': 'text/cache-manifest',
        '.html': 'text/html',
        '.png': 'image/png',
        '.jpg': 'image/jpg',
        '.svg': 'image/svg+xml',
        '.css': 'text/css',
        '.js': 'application/x-javascript',
        '.wasm': 'application/wasm',
        '.json': 'application/json',
        '.xml': 'application/xml',
    }

with socketserver.TCPServer(("localhost", PORT), HttpRequestHandler) as httpd:
    print(f"serving at http://localhost:{PORT}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
```
Assuming you named the new file `server.py`, run `py server.py` from that same terminal window.

Credit: [this gist](https://gist.github.com/HaiyangXu/ec88cbdce3cdbac7b8d5).

Hope this helps!

**Comment by XenoMustache** [comment]
Thanks, this worked perfectly!
